name: PR checks

on:
  pull_request:
    branches:
      - main

env:
  GO111MODULE: on
  MINIKUBE_WANTUPDATENOTIFICATION: false
  MINIKUBE_WANTREPORTERRORPROMPT: false
  SDK_VERSION: "1.25.0"
  K8S_VERSION: "1.25.0"
  MINIKUBE_VERSION: "1.28.0"
  TEST_ACCEPTANCE_CLI: "kubectl"
  TEST_RESULTS: "out/acceptance-tests"

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.19"

      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Unit Tests with Code Coverage
        run: |
          make test

  acceptance:
    name: Acceptance Tests
    runs-on: ubuntu-20.04
    timeout-minutes: 90

    env:
      EXTRA_BEHAVE_ARGS: "--tags=~@disable-github-actions"

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Setup-cli
        uses: ./.github/actions/setup-cli
        with:
          start-minikube: true

      - name: Acceptance tests
        timeout-minutes: 60
        run: |
          make test-acceptance

      - uses: actions/upload-artifact@v3
        if: ${{ steps.check-skip-acceptance.outputs.can_skip != 'true' && always() }}
        with:
          name: acceptance-test-results
          path: ${{ env.TEST_RESULTS }}

